apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-api
  labels:
    app: serviceapisvc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: serviceapisvc
  template:
    metadata:
      labels:
        app: serviceapisvc
    spec:
      containers:
      - name: service-api
        image: 526326026737.dkr.ecr.us-east-2.amazonaws.com/service-api:7493f95
        ports:
        - containerPort: 80
